development:
  adapter: postgresql
  database: autosc2app
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: autosc2app_test
  host: localhost
  pool: 5
  timeout: 5000

cucumber:
  <<: *test