development:
  adapter: postgresql
  database: ruby_sample_app
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: ruby_sample_app_test
  host: localhost
  pool: 5
  timeout: 5000

cucumber:
  <<: *test